# For more information: https://laravel.com/docs/sail
version: '3'
services:
  app:
    image: guoxiangke/lms2021
    build:
      context: .
    ports:
      - 8008:80
    volumes:
      - ./laravel/app:/var/www/html/app
      - ./laravel/config:/var/www/html/config
      - ./laravel/database:/var/www/html/database
      - ./laravel/routes:/var/www/html/routes
      - ./laravel/storage:/var/www/html/storage
      - ./laravel/vendor:/var/www/html/vendor